CC = gcc
FLAGS = -Wall
CGIBIN = .

all:
	$(CC) $(FLAGS) -lcgi redirect.c -o $(CGIBIN)/redirect.cgi

	@echo 
	@echo Example compiled. 
	@echo Now copy redirect.cgi file to your webserver cgi-bin directory
	@echo and call it 
	@echo 
