CC = gcc
FLAGS = -Wall
CGIBIN = .

all:
	$(CC) $(FLAGS) -lcgi multiple.c -o $(CGIBIN)/multiple.cgi

	@echo 
	@echo Example compiled. Now copy multiple.cgi and 
	@echo *.html files to your webserver cgi-bin directory
	@echo To test, call multiple.cgi application
	@echo 
